version: '3.9'
services:
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 120
    ports:
      - 22:22
  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80